package CacheWolf;
import ewe.util.*;
import ewe.sys.*;
import ewe.io.*;
import ewe.filechooser.*;
import ewe.ui.*;
import ewe.util.*;
/**
*	Class to export the cache database to a GPX file with gc.com
*	extensions.<br>
*	Export of logs is not that nice. The cause is that CacheWolf does not spider
*	logs individually, rather all logs as a single entity.
*	ClassID = 2000
*/
public class GPXExporter{
//	TODO Exportanzahl anpassen: Bug: 7351
	Vector cacheDB;
	Preferences pref;
	Profile profile;
	ProgressBarForm pbf = new ProgressBarForm();
	
	public GPXExporter(Preferences p, Profile prof){
		pref = p;
		profile=prof;
		cacheDB = profile.cacheDB;
	}
	
	public void doIt(int variant){
		CacheHolder ch;
		String cwd= File.getProgramDirectory();
		File saveTo = new File(cwd + "/temp.gpx");
		if(variant == 1) {
			FileChooser fc = new FileChooser(FileChooser.SAVE, profile.dataDir);
			fc.setTitle("Select target file:");
			if(fc.execute() != FormBase.IDCANCEL) saveTo = fc.getChosenFile();
		}
		try{
			PrintWriter outp =  new PrintWriter(new BufferedWriter(new FileWriter(saveTo)));
			outp.print("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n");
			outp.print("<gpx xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" version=\"1.0\" creator=\"Groundspeak Pocket Query\" xsi:schemaLocation=\"http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd http://www.groundspeak.com/cache/1/0 http://www.groundspeak.com/cache/1/0/cache.xsd\" xmlns=\"http://www.topografix.com/GPX/1/0\">\r\n");
			outp.print("  <desc>Geocache file generated by CacheWolf</desc>\r\n");
			outp.print("  <author>CacheWolf</author>\r\n");
			outp.print("  <email>test@test.com</email>\r\n");
			Time tim = new Time();
			tim = tim.setFormat("yyyy-MM-dd");
			tim = tim.setToCurrentTime();
			outp.print(" <time>"+tim.toString()+"T00:00:00.0000000-07:00</time>\r\n");
			ParseLatLon pll;
			String msg;
			for(int i = 0; i<cacheDB.size(); i++){
				if (i%5 == 0){
					msg = "Export " + Convert.toString(i) + " of " + Convert.toString(cacheDB.size());
					pbf.display("GPX Export",msg,null);
				}
				ch=(CacheHolder)cacheDB.get(i);
				if(ch.is_black == false && ch.is_filtered == false){
					//KHF read cachedata only if needed 
					ch.readCache(profile.dataDir);
					pll = new ParseLatLon(ch.LatLon, ".");
					pll.parse();
					outp.print("  <wpt lat=\""+pll.getLatDeg()+"\" lon=\""+pll.getLonDeg()+"\">\r\n");
					if (ch.DateHidden.length()> 0){
						tim.parse(ch.DateHidden, "M/d/y");
					}
					else {
						tim.setText("2000-01-01");
					}
					outp.print("    <time>"+tim.toString()+"T00:00:00.0000000-07:00</time>\r\n");
					outp.print("    <name>"+ch.wayPoint+"</name>\r\n");
					outp.print("    <desc>"+SafeXML.cleanGPX(ch.CacheName)+" by "+SafeXML.cleanGPX(ch.CacheOwner)+"</desc>\r\n");
					outp.print("    <url>http://www.geocaching.com/seek/cache_details.aspx?wp="+ch.wayPoint+"&amp;Submit6=Find</url>\r\n");
					outp.print("    <urlname>"+SafeXML.cleanGPX(ch.CacheName)+" by "+SafeXML.cleanGPX(ch.CacheOwner)+"</urlname>\r\n");
					outp.print("    <sym>Geocache</sym>\r\n");
					outp.print("    <type>Geocache|"+CacheType.transType(ch.type)+"</type>\r\n");
					//outp.print("    <type>Geocache|Geocache</type>\r\n");
					String dummyAvailable = ch.is_available ? "True":"False";
					String dummyArchived = ch.is_archived ? "True":"False";
					outp.print("    <groundspeak:cache available=\""+ dummyAvailable + "\" archived=\"" + dummyArchived+ "\" xmlns:groundspeak=\"http://www.groundspeak.com/cache/1/0\">\r\n");
					outp.print("      <groundspeak:name>"+SafeXML.cleanGPX(ch.CacheName)+"</groundspeak:name>\r\n");
					outp.print("      <groundspeak:placed_by>"+SafeXML.cleanGPX(ch.CacheOwner)+"</groundspeak:placed_by>\r\n");
					outp.print("      <groundspeak:owner>"+SafeXML.cleanGPX(ch.CacheOwner)+"</groundspeak:owner>\r\n");
					outp.print("      <groundspeak:type>"+CacheType.transType(ch.type)+"</groundspeak:type>\r\n");
					outp.print("      <groundspeak:container>"+ch.CacheSize+"</groundspeak:container>\r\n");
					//KHF use '.' instead of ','
					outp.print("      <groundspeak:difficulty>"+ch.hard.replace(',','.')+"</groundspeak:difficulty>\r\n");
					outp.print("      <groundspeak:terrain>"+ch.terrain.replace(',','.')+"</groundspeak:terrain>\r\n");
					String dummyHTML = ch.is_HTML ? "True":"False";
					outp.print("      <groundspeak:long_description html=\"" + dummyHTML + "\">\r\n");
					outp.print("      "+SafeXML.cleanGPX(ch.LongDescription));
					outp.print("      \n</groundspeak:long_description>\r\n");
					outp.print("	  <groundspeak:encoded_hints>"+SafeXML.cleanGPX(Common.rot13(ch.Hints))+"</groundspeak:encoded_hints>\r\n");
					outp.print("      <groundspeak:logs>\r\n");
					/*
					for(int j = 0; j<holder.CacheLogs.size(); j++){
						outp.print("	    <groundspeak:log>\r\n");
						outp.print("            <groundspeak:date>");
						outp.print("T08:00:00</groundspeak:date>\r\n");
						outp.print("<groundspeak:finder>");
						outp.print("</groundspeak:finder>");
						outp.print("		<groundspeak:text encoded=\"False\">\r\n");
						outp.print("		</groundspeak:text>\r\n");
						outp.print("	    </groundspeak:log>\r\n");
					}
					*/
					outp.print("      </groundspeak:logs>\r\n");
					outp.print("      <groundspeak:travelbugs />\r\n");
					outp.print("    </groundspeak:cache>\r\n");
					outp.print("  </wpt>\r\n");
				} // if holder ==
			}//for
			pbf.clear();
			outp.print("</gpx>");
			outp.close();
		}catch(Exception e){
			Vm.debug("Problem writing to GPX file");
			e.printStackTrace();
		}//try
	}
}
