<tmpl_par name="charset" value="UTF8">
<tmpl_par name="newline" value="CRLF">
<tmpl_par name="decsep" value=".">
<tmpl_par name="Out" value="*.gpx">
<?xml version="1.0" encoding="utf-8"?<br>
<gpx xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="1.0" creator="Groundspeak Pocket Query" xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd http://www.groundspeak.com/cache/1/0/1 http://www.groundspeak.com/cache/1/0/1/cache.xsd" xmlns="http://www.topografix.com/GPX/1/0"><br>
  <name><tmpl_var NAME></name><br>
  <desc>Geocache file generated by Groundspeak</desc><br>
  <author>Groundspeak</author><br>
  <email>contact@cachewolf.de</email><br>
  <keywords>cache, geocache, groundspeak</keywords><br>
<tmpl_loop cache_index>
  <tmpl_if __FIRST__><time><tmpl_var NOW_DATE>T<tmpl_var NOW_TIME>:00Z</time><br>
  </tmpl_if>
<wpt lat="<tmpl_var LAT>" lon="<tmpl_var LON>"><br>
    <time><tmpl_var DATE>T07:00:00Z</time><br>
    <name><tmpl_var WAYPOINT></name><br>
    <desc><tmpl_var NAME> (<tmpl_var DIFFICULTY>/<tmpl_var TERRAIN>)</desc><br>
    <url><tmpl_var URL></url><br>
    <urlname><tmpl_var NAME></urlname><br>
    <sym><tmpl_var SYM></sym><br>
    <type><tmpl_var TYPE></type><br>
    <groundspeak:cache id="<tmpl_var CACHEID>" available="<tmpl_var AVAILABLE>" archived="<tmpl_var ARCHIVED>" xmlns:groundspeak="http://www.groundspeak.com/cache/1/0/1"><br>
      <groundspeak:name><tmpl_var NAME></groundspeak:name><br>
      <groundspeak:placed_by><tmpl_var OWNER></groundspeak:placed_by><br>
      <groundspeak:owner id="31415"><tmpl_var OWNER></groundspeak:owner><br>
      <groundspeak:type><tmpl_var GSTYPE></groundspeak:type><br>
      <groundspeak:container><tmpl_var SIZE></groundspeak:container><br>
      <groundspeak:attributes><br>
        <tmpl_loop ATTRIBUTES>
        <groundspeak:attribute id="<tmpl_var GCID>" inc="<tmpl_var INC>"><tmpl_var INFO></groundspeak:attribute><br>
        </tmpl_loop>
       </groundspeak:attributes><br>
      <groundspeak:difficulty><tmpl_var DIFFICULTY></groundspeak:difficulty><br>
      <groundspeak:terrain><tmpl_var TERRAIN></groundspeak:terrain><br>
      <groundspeak:country><tmpl_var COUNTRY></groundspeak:country><br>
      <groundspeak:state><tmpl_var STATE></groundspeak:state><br>
      <groundspeak:short_description html="<tmpl_var HTML>"><tmpl_var NAME> (<tmpl_var DIFFICULTY>/<tmpl_var TERRAIN>)</groundspeak:short_description><br>
      <groundspeak:long_description html="<tmpl_var HTML>"<tmpl_var DESCRIPTION></groundspeak:long_description><br>
      <groundspeak:encoded_hints><tmpl_var DESCRYPTEDHINTS></groundspeak:encoded_hints><br>
      <groundspeak:logs><br>
        <groundspeak:log id="<tmpl_var WAYPOINT>0"><br>
          <groundspeak:finder id="0">CacheWolf</groundspeak:finder><br>
          <groundspeak:text encoded="False"><tmpl_loop ATTRIBUTES>&lt;br /&gt;<tmpl_var INC2TXT>&amp;nbsp;:<tmpl_var INFO>&lt;br /&gt;</tmpl_loop></groundspeak:text><br>
        </groundspeak:log><br>
      <tmpl_loop LOGS>  <groundspeak:log id="<tmpl_var WAYPOINT><tmpl_var __COUNTER__>"><br>
          <groundspeak:date><tmpl_var DATE>T19:00:00Z</groundspeak:date><br>
          <groundspeak:type><tmpl_var LOGTYPE></groundspeak:type><br>
          <groundspeak:finder id="0"><tmpl_var LOGGER></groundspeak:finder><br>
          <groundspeak:text encoded="False"><tmpl_var MESSAGE></groundspeak:text><br>
        </groundspeak:log><br>
      </tmpl_loop></groundspeak:logs><br>
      <groundspeak:travelbugs /><br>
    </groundspeak:cache><br>
  </wpt><br>
</tmpl_loop>
</gpx><br>

